#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/2e6fb92c-afd7-4a76-ac73-79d4fa37d930 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

 int nivel_Graunte;
CloudSchedule feed_schedule1;
CloudSchedule feed_schedule2;
bool manual_feed;
bool senzor_proximitate;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

bool comanda_trimisa_deja = false;


void sendSignalFeeder(){
  Serial.write('H');
  Serial.write(nivel_Graunte + '0');
  
}

void sendSignalSensor(){
  Serial.write('U');
  if(senzor_proximitate){
    Serial.write('1');
  }
  else{
    Serial.write('0');
  }
  
}

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  delay(1500); 
  // Defined in thingProperties.h
  initProperties();
  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  delay(1500);
  sendSignalSensor();

}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  bool e_timpul_de_masa = feed_schedule1.isActive() || feed_schedule2.isActive();

  if( e_timpul_de_masa){

    if(!comanda_trimisa_deja){
      sendSignalFeeder();
      comanda_trimisa_deja = true;
    } 
  }
    else {
      comanda_trimisa_deja = false;
  }
}


/*
  Since ManualFeed is READ_WRITE variable, onManualFeedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onManualFeedChange()  {
  // Add your code here to act upon ManualFeed change
  if (manual_feed == true){

    sendSignalFeeder();

    manual_feed = false;
  }
}

/*
  Since FeedSchedule1 is READ_WRITE variable, onFeedSchedule1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onFeedSchedule1Change()  {
  // Add your code here to act upon FeedSchedule1 change
}

/*
  Since FeedSchedule2 is READ_WRITE variable, onFeedSchedule2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onFeedSchedule2Change()  {
  // Add your code here to act upon FeedSchedule2 change
}

void onSenzorProximitateChange()  {

sendSignalSensor();

}

void onNivelGraunteChange(){

}